pipeline {
    agent any
    stages {
        stage('git repo & clean') {
            steps {
               bat "rmdir  /s /q SpringBootSecurityExample"
                bat "git clone "
                bat "mvn clean -f SpringBootSecurityExample"
            }
        }
        stage('install') {
            steps {
                bat "mvn install -f SpringBootSecurityExample"
            }
        }
        stage('test') {
            steps {
                bat "mvn test -f SpringBootSecurityExample"
            }
        }
        stage('package') {
            steps {
                bat "mvn package -f SpringBootSecurityExample"
            }
        }
    }
}
